# Note  : *** the batch_size should be equal to the gpus number at the test phase!!! ***
data_cfg:
  dataset_name: TUM_GAID
  dataset_root: your_path
  dataset_partition: ./datasets/TUM_GAID/TUM_GAID.json
  num_workers: 1
  remove_no_gallery: false
  test_dataset_name: TUM_GAID

evaluator_cfg:
  enable_float16: false 
  restore_ckpt_strict: true
  restore_hint: 80000
  save_name: PoseGaitGL
  eval_func: evaluation_tum_gaid
  sampler:
    batch_size: 8
    sample_type: all_ordered
    type: InferenceSampler
  transform:
    - img_w: 64
      disvor: 1.0
      type: BaseSilCuttingTransform

loss_cfg:
  - loss_term_weight: 1.0
    margin: 0.2
    type: TripletLoss
    log_prefix: triplet
  - loss_term_weight: 1.0
    scale: 1
    type: CrossEntropyLoss
    log_accuracy: true
    label_smooth: true # Set by default to 0.1
    log_prefix: softmax

model_cfg:
  model: PoseGaitGL
  channels: [32, 64, 128]
  class_num: 150
  repeat_layers:
    GLConvA1: 2
  num_in_channels: 13 # full-body (1) + limbs (4) + middle-limbs (8)

optimizer_cfg:
  lr: 1.0e-4
  solver: Adam
  weight_decay: 5.0e-4

scheduler_cfg:
  gamma: 0.1
  milestones:
    - 70000
  scheduler: MultiStepLR

trainer_cfg:
  enable_float16: false
  with_test: false
  log_iter: 100
  restore_ckpt_strict: true
  restore_hint: 0
  save_iter: 10000
  save_name: PoseGaitGL
  sync_BN: true
  total_iter: 80000
  sampler:
    batch_shuffle: true
    batch_size:
      - 8
      - 8
    frames_num_fixed: 30
    frames_skip_num: 0
    sample_type: fixed_ordered
    type: TripletSampler
  transform:
    - img_w: 64
      disvor: 1.0
      type: BaseSilCuttingTransform
