# Note  : *** the batch_size should be equal to the gpus number at the test phase!!! ***
data_cfg:
  dataset_name: CASIA-B
  dataset_root: your_path
  dataset_partition: ./datasets/CASIA-B/CASIA-B.json
  num_workers: 1
  remove_no_gallery: false
  test_dataset_name: CASIA-B
  sel_channel_idx: [0, 2, 3, 5, 6, 8, 9, 11, 12, 14, 15, 17, 18, 20, 21, 23, 24, 26, 27, 29, 30, 32, 33, 35, 36, 38] # Only channels IV are used

evaluator_cfg:
  enable_float16: false
  restore_ckpt_strict: true
  restore_hint: 120000
  save_name: GaitPart
  sampler:
    batch_size: 16
    sample_type: all_ordered
    type: InferenceSampler
  metric: euc # cos

loss_cfg:
  loss_term_weight: 1.0
  margin: 0.2
  type: TripletLoss
  log_prefix: triplet

model_cfg:
  model: GaitPart
  backbone_cfg:
    in_channels: 26 # full-body (2 * 1) + limbs (2 * 4) + middle-limbs (2 * 8)
    layers_cfg:
      - BC-32
      - BC-32
      - M
      - FC-64-2
      - FC-64-2
      - M
      - FC-128-3
      - FC-128-3
    type: Plain
  SeparateFCs:
    in_channels: 128
    out_channels: 128
    parts_num: 16
  bin_num:
    - 16
  displayed_channels: [12, 25]

optimizer_cfg:
  lr: 0.0001
  momentum: 0.9
  solver: Adam
  weight_decay: 0.0

scheduler_cfg:
  gamma: 0.1
  milestones:
    - 100000
  scheduler: MultiStepLR

trainer_cfg:
  enable_float16: true
  log_iter: 100
  with_test: false
  restore_ckpt_strict: true
  restore_hint: 0
  save_iter: 10000
  save_name: GaitPart
  sync_BN: false
  total_iter: 120000
  sampler:
    batch_shuffle: false
    batch_size:
      - 8
      - 16
    frames_num_fixed: 30
    frames_num_max: 50
    frames_num_min: 25
    frames_skip_num: 10
    sample_type: fixed_ordered
    type: TripletSampler

